//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_mvc_2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class laporan
    {
        public int id_laporan { get; set; }
        public int id_outbond { get; set; }
        public int id_pelanggan { get; set; }
        public string keterangan { get; set; }
        public System.DateTime tgl_akhir { get; set; }
        public System.DateTime tgl_mulai { get; set; }
        public System.DateTime tgl_pesan { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> harga { get; set; }
        public Nullable<int> jumlah { get; set; }
    
        public virtual outbond outbond { get; set; }
        public virtual pelanggan pelanggan { get; set; }
    }
}
